// Self-host the Latin subsets of Fable's typefaces so first paint needs no third-party round trips.
// Run once (or after changing families); outputs under public/fonts/ and src/fonts.css are committed.
import { writeFile, mkdir } from 'node:fs/promises';
const families = 'family=Cormorant+Garamond:ital,wght@0,500;0,600;1,500&family=EB+Garamond:ital,wght@0,400;0,500;0,600;1,400&family=IBM+Plex+Mono:wght@400;500';
const ua = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36';
const css = await (await fetch(`https://fonts.googleapis.com/css2?${families}&display=swap`, { headers: { 'User-Agent': ua } })).text();
await mkdir('public/fonts', { recursive: true });
const blocks = [...css.matchAll(/\/\* ([a-z-]+) \*\/\s*@font-face \{([\s\S]*?)\}/g)];
let out = '/* Generated by scripts/fetch-fonts.mjs — Latin subsets, self-hosted. */\n';
for (const [, subset, body] of blocks) {
  if (!['latin', 'latin-ext'].includes(subset)) continue;
  const family = body.match(/font-family: '([^']+)'/)[1], style = body.match(/font-style: (\w+)/)[1], weight = body.match(/font-weight: (\d+)/)[1];
  const url = body.match(/url\(([^)]+)\)/)[1];
  const name = `${family.toLowerCase().replace(/\s+/g, '-')}-${weight}${style === 'italic' ? 'i' : ''}-${subset}.woff2`;
  await writeFile(`public/fonts/${name}`, Buffer.from(await (await fetch(url)).arrayBuffer()));
  out += `@font-face{font-family:'${family}';font-style:${style};font-weight:${weight};font-display:swap;src:url(/fonts/${name}) format('woff2');${body.match(/unicode-range: [^;]+;/)[0]}}\n`;
}
await writeFile('src/fonts.css', out);
console.log(`Wrote ${out.split('\n').length - 2} font faces.`);
