(function () {
  const copy = {
    en:{continuing:'The rest of your fable is on its way…',illustration:'An illustration from this fable.',kicker:'Learn through stories',title:'What would you',title2:'like to',accent:'understand?',sub:'We’ll turn it into an illustrated fable.',placeholder:'An idea you’d like to understand…',create:'Create a fable',sample:'Read a sample',sampleTitle:'The Hall of Affairs',sampleMeta:'How AI agents work · 5 min',world:'Story world',library:'Your fables',empty:'Your stories will appear here.',coming:'Creation is being connected. The sample is ready to read.',end:'The end',keep:'A story to keep.',take:'Take it with you. Pass it on.',download:'Download fable',share:'Share fable',next:'Create another fable',saved:'Saved privately. Share only when you choose.',offline:'Offline book',offlineSub:'Illustrations included · opens in any browser',pdf:'Save as PDF',pdfSub:'Opens your browser’s print view',copy:'Copy link',publish:'Create share link',revoke:'Stop sharing',private:'Only you can read this story until you share a link.',public:'Anyone with this link can read the story.',copied:'Link copied.',revokeDone:'Sharing is off. The old link no longer works.',loading:'Opening your fable…',working:'Your fable is being created. It will keep working if you leave.',failed:'This fable is incomplete. Finished scenes and pictures are saved.',close:'Close',back:'Home'},
    fr:{continuing:'La suite de votre fable arrive…',illustration:'Une illustration de cette fable.',kicker:'Apprendre par les histoires',title:'Que souhaitez-vous',title2:'',accent:'comprendre ?',sub:'Nous en ferons une fable illustrée.',placeholder:'Une idée que vous aimeriez comprendre…',create:'Créer une fable',sample:'Lire un exemple',sampleTitle:'La salle des affaires',sampleMeta:'Comprendre les agents IA · 5 min',world:'Univers',library:'Vos fables',empty:'Vos histoires apparaîtront ici.',coming:'La création arrive bientôt. L’exemple est prêt à lire.',end:'Fin',keep:'Une histoire à garder.',take:'Emportez-la. Partagez-la.',download:'Télécharger',share:'Partager',next:'Créer une autre fable',saved:'Enregistrée en privé. Partagez si vous le souhaitez.',offline:'Livre hors ligne',offlineSub:'Illustrations incluses · dans tout navigateur',pdf:'Enregistrer en PDF',pdfSub:'Ouvre la fenêtre d’impression',copy:'Copier le lien',publish:'Créer un lien',revoke:'Arrêter le partage',private:'Cette histoire reste privée jusqu’au partage du lien.',public:'Toute personne disposant du lien peut lire l’histoire.',copied:'Lien copié.',revokeDone:'Le partage est désactivé.',loading:'Ouverture de votre fable…',working:'Votre fable continue à se créer même si vous partez.',failed:'Cette fable est incomplète. Les scènes et images terminées sont enregistrées.',close:'Fermer',back:'Accueil'},
    da:{continuing:'Resten af din fabel er på vej…',illustration:'En illustration fra denne fabel.',kicker:'Lær gennem historier',title:'Hvad vil du gerne',title2:'',accent:'forstå?',sub:'Vi gør det til en illustreret fabel.',placeholder:'En idé, du gerne vil forstå…',create:'Skab en fabel',sample:'Læs et eksempel',sampleTitle:'Salen for Anliggender',sampleMeta:'Sådan virker AI-agenter · 5 min',world:'Fortællingens verden',library:'Dine fabler',empty:'Dine historier vises her.',coming:'Oprettelse er snart klar. Læs eksemplet imens.',end:'Slut',keep:'En historie at gemme.',take:'Tag den med. Giv den videre.',download:'Hent fabel',share:'Del fabel',next:'Skab en ny fabel',saved:'Gemt privat. Del, når du ønsker det.',offline:'Offlinebog',offlineSub:'Med illustrationer · åbnes i en browser',pdf:'Gem som PDF',pdfSub:'Åbner browserens udskriftsvindue',copy:'Kopiér link',publish:'Opret delingslink',revoke:'Stop deling',private:'Kun du kan læse historien, indtil du deler et link.',public:'Alle med linket kan læse historien.',copied:'Link kopieret.',revokeDone:'Deling er slået fra.',loading:'Åbner din fabel…',working:'Din fabel bliver færdig, selvom du forlader siden.',failed:'Fablen er ikke færdig. De færdige scener og billeder er gemt.',close:'Luk',back:'Hjem'},
    zh:{continuing:'接下来的故事正在赶来……',illustration:'这则寓言的插画。',kicker:'通过故事学习',title:'你想',title2:'',accent:'理解什么？',sub:'让一个想法，成为一则插画寓言。',placeholder:'写下你想理解的一个概念……',create:'创作寓言',sample:'阅读示例',sampleTitle:'应事斋',sampleMeta:'认识 AI 智能体 · 5 分钟',world:'故事世界',library:'我的寓言',empty:'你的故事将保存在这里。',coming:'创作功能正在接入。你可以先阅读示例。',end:'故事完',keep:'把故事带走。',take:'珍藏，也分享。',download:'下载寓言',share:'分享寓言',next:'再创作一则',saved:'已私密保存。分享由你决定。',offline:'离线故事书',offlineSub:'包含插画 · 在浏览器中打开',pdf:'另存为 PDF',pdfSub:'打开浏览器打印窗口',copy:'复制链接',publish:'创建分享链接',revoke:'停止分享',private:'创建分享链接前，只有你能阅读。',public:'任何获得链接的人都可以阅读。',copied:'链接已复制。',revokeDone:'分享已关闭，旧链接不再有效。',loading:'正在打开寓言……',working:'寓言正在创作。离开页面后仍会继续。',failed:'这则寓言尚未完成，已完成的场景和插画均已保存。',close:'关闭',back:'首页'},
  };
  window.FABLE_HOME_COPY=copy;
  const worlds=['Chinese classical','Greek myth','Fairy tale','Contemporary'];
  function Overlay({title,onClose,children}) {
    const ref=React.useRef(null);
    React.useEffect(()=>{ref.current.showModal();},[]);
    return <dialog ref={ref} className="overlay-card fable-modal" role="dialog" aria-label={title} onCancel={onClose} onClose={onClose} onKeyDown={e=>e.stopPropagation()}><button className="iconbtn fable-modal-close" aria-label={copy[document.documentElement.lang.split('-')[0]]?.close||'Close'} onClick={onClose}><Icon name="x"/></button>{children}</dialog>;
  }
  function Home({onWeave,onOpenBook,onOpenSaved,theme,setTheme,lang,setLang,T}) {
    const C=copy[lang], [topic,setTopic]=React.useState(''),[world,setWorld]=React.useState(worlds[0]);
    const [enabled,setEnabled]=React.useState(false),[stories,setStories]=React.useState([]),[library,setLibrary]=React.useState(false);
    React.useEffect(()=>{let active=true;fetch('/api/config').then(r=>r.json()).then(d=>{if(active)setEnabled(d.generation_enabled);}).catch(()=>{});
      fetch('/api/stories').then(r=>r.json()).then(d=>{if(active)setStories(d.stories||[]);}).catch(()=>{});return()=>{active=false;};},[]);
    return <div className="fable-home" lang={htmlLang(lang)}><header className="fable-home-bar"><Logo lang={lang}/><div className="fable-home-tools">{stories.length>0&&<button className="btn btn--quiet" onClick={()=>setLibrary(true)}>{C.library}</button>}<LangToggle lang={lang} setLang={setLang}/><ThemeToggle theme={theme} setTheme={setTheme} lang={lang}/></div></header>
      <main className="fable-home-main"><div className="fable-question"><p className="kicker">{C.kicker}</p><h1>{C.title}<br/>{C.title2} <em>{C.accent}</em></h1><p className="fable-sub">{C.sub}</p>
        <form className="fable-bubble" onSubmit={e=>{e.preventDefault();if(enabled&&topic.trim().length>=2)onWeave({concept:topic.trim(),setting:world});}}>
          <label className="sr-only" htmlFor="fable-idea">{C.placeholder}</label><textarea id="fable-idea" rows="3" placeholder={C.placeholder} value={topic} onChange={e=>setTopic(e.target.value)} minLength={2} maxLength={2000} required/>
          <div className="fable-bubble-foot"><select value={world} onChange={e=>setWorld(e.target.value)} aria-label={C.world}>{worlds.map((w,i)=><option key={w} value={w}>{FABLE.settings[lang][i]}</option>)}</select><button className="fable-send" type="submit" disabled={!enabled||topic.trim().length<2}>{C.create}<Icon name="arrowR" size={17}/></button></div>
        </form>{!enabled&&<p className="fable-availability" role="status">{C.coming}</p>}
      </div><button className="fable-sample" data-ob="sample" onClick={()=>onOpenBook(false)} aria-label={T.readSample}><img src="/art/cover.png" alt=""/><div className="fable-sample-caption"><div><p className="kicker">{C.sample}</p><h2>{C.sampleTitle}</h2><p>{C.sampleMeta}</p></div><span aria-hidden="true">↗</span></div></button></main>
      {library&&<Overlay onClose={()=>setLibrary(false)} title={C.library}><h2 className="fable-dialog-title">{C.library}</h2>{stories.map(s=><button className="fable-library-row" key={s.id} onClick={()=>onOpenSaved(s.id)}><strong>{s.title||s.concept}</strong><span>{s.status==='completed'?'↗':s.status==='failed'?'Saved text':C.working}</span></button>)}</Overlay>}
    </div>;
  }
  async function offlineBook(pages,lang) {
    const images=[...new Set(pages.map(p=>p.image).filter(Boolean))], data={};
    await Promise.all(images.map(async src=>{const response=await fetch(src);if(!response.ok)throw new Error('Could not load the illustration.');const blob=await response.blob();data[src]=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(blob);});}));
    const escape=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
    let previous=null;
    const content=pages.map(p=>{let picture='';if(p.image&&p.image!==previous){picture=`<img src="${data[p.image]}" alt="${escape(p.title)}">`;previous=p.image;}return `${p.kind==='Cover'?`<h1>${escape(p.title)}</h1>`:p.kind==='Lesson'?`<h2>${escape(FABLE.ui[lang].afterStory)}</h2>`:''}${picture}${p.raw?FABLE.renderMarkdown(p.raw):''}`;}).join('');
    return `<!doctype html><html lang="${htmlLang(lang)}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escape(pages[0].title)} — Fable</title><style>body{margin:0;color:#30281e;background:#eee5d3;font:20px/1.65 Georgia,serif}main{max-width:760px;margin:auto;padding:50px 24px}h1{font-size:52px;line-height:1.1}h2{margin-top:50px}img{width:100%;margin:24px 0}small{font:12px Arial,sans-serif}li{margin-bottom:14px}@media print{body{background:white;font-size:12pt}main{padding:0}h2{break-before:page}img{max-height:65vh;object-fit:contain}p,li{orphans:3;widows:3}}</style></head><body><main><small>FABLE</small>${content}</main></body></html>`;
  }
  function Ending({pages,lang,onExit,bookInfo}) {
    const C=copy[lang],[modal,setModal]=React.useState(null),[notice,setNotice]=React.useState(''),[link,setLink]=React.useState(bookInfo?.shareURL||''),[busy,setBusy]=React.useState(false);
    const shared=new URLSearchParams(location.search).get('share');
    const storyId=bookInfo?.storyId;
    async function download(pdf=false) {
      const win=pdf?window.open('about:blank','_blank'):null;
      if(pdf&&!win){setNotice('Allow a new tab to open the print view.');return;}
      setBusy(true);setNotice('');
      try{const html=await offlineBook(pages,lang);if(win){win.document.open();win.document.write(html);win.document.close();await Promise.all([...win.document.images].map(i=>i.decode()));win.focus();win.print();}
        else{const url=URL.createObjectURL(new Blob([html],{type:'text/html'})),a=document.createElement('a');a.href=url;a.download='fable.html';a.click();setTimeout(()=>URL.revokeObjectURL(url),60000);}}
      catch(e){win?.close();setNotice(e.message);}finally{setBusy(false);}
    }
    async function share() {
      setBusy(true);setNotice('');
      try{let url=link;if(!url){if(shared)url=`${location.origin}/?share=${encodeURIComponent(shared)}#read/cover`;
          else if(storyId){const r=await fetch(`/api/stories/${storyId}/share`,{method:'POST'});const d=await r.json();if(!r.ok)throw new Error(d.error);url=d.url;}
          else url=`${location.origin}/?lang=${lang}#read/cover`;setLink(url);}
        try{await navigator.clipboard.writeText(url);setNotice(C.copied);}catch{setNotice(C.copy);}}
      catch(e){setNotice(e.message);}finally{setBusy(false);}
    }
    async function revoke(){setBusy(true);try{const r=await fetch(`/api/stories/${storyId}/share`,{method:'DELETE'});if(!r.ok)throw new Error('Please try again.');setLink('');setNotice(C.revokeDone);}catch(e){setNotice(e.message);}finally{setBusy(false);}}
    return <div className="fable-ending"><div className="fable-rule"/><p className="kicker">{C.end}</p><h2>{C.keep}</h2><p className="fable-closing">{C.take}</p><div className="fable-end-actions"><button className="btn btn--primary" onClick={()=>{setModal('download');setNotice('');}}>{C.download} ↓</button><button className="btn" disabled={bookInfo?.partial} onClick={()=>{setModal('share');setNotice('');}}>{C.share} ↗</button></div>{storyId&&!shared&&<p className="fable-saved">{bookInfo.partial?C.failed:C.saved}</p>}<button className="fable-next" onClick={onExit}>{C.next} →</button>
      {modal&&<Overlay title={modal==='share'?C.share:C.download} onClose={()=>setModal(null)}><h2 className="fable-dialog-title">{modal==='share'?C.share:C.download}</h2>{modal==='download'?<><button className="fable-export" disabled={busy} onClick={()=>download()}>{C.offline}<span>{C.offlineSub}</span></button><button className="fable-export" disabled={busy} onClick={()=>download(true)}>{C.pdf}<span>{C.pdfSub}</span></button></>:<><p className="fable-share-copy">{link||shared||!storyId?C.public:C.private}</p>{link&&<input className="fable-share-input" aria-label={C.copy} readOnly value={link} onFocus={e=>e.target.select()}/>}<button className="btn btn--primary" disabled={busy} onClick={share}>{link||shared||!storyId?C.copy:C.publish}</button>{link&&storyId&&!shared&&<button className="btn btn--quiet" disabled={busy} onClick={revoke}>{C.revoke}</button>}</>}<p role="status" className="fable-saved">{notice}</p></Overlay>}
    </div>;
  }
  window.FableHomepage=Home;window.FableEnding=Ending;
})();
