// Copy for the sample-first preview and reading controls.
const previewCopy = {
  "en": {
    "shelf": "Home",
    "previewLabel": "An illustrated learning preview",
    "previewTitle": "Understand AI through a fable.",
    "previewSub": "Meet the mind, memory, and tools behind an AI agent — inside the Hall of Affairs.",
    "readSample": "Read the sample",
    "resume": "Continue reading",
    "sampleMeta": "An illustrated story, followed by the explanation",
    "comingSoon": "Create your own — coming soon",
    "previewNote": "Story and image generation are not available yet. This sample is ready to read.",
    "scrollCue": "Scroll to continue",
    "endLabel": "Finish",
    "decodedWord": "Explanation",
    "afterStory": "The story, explained",
    "figureAlt": "A cutaway of the Hall of Affairs: a scholar at the center, surrounded by the context desk, memory archive, runners, steward, and safeguards.",
    "figureCaption": "One house, many parts. The story’s characters represent the layers below.",
    "languageLabel": "Language",
    "lightLabel": "Switch to light",
    "darkLabel": "Switch to dark",
    "closeLabel": "Close",
    "guideLabel": "Guide me",
    "guideClose": "Close guide",
    "guideSkip": "Skip",
    "guideBack": "Back",
    "guideNext": "Next",
    "guideFinish": "Finish",
    "guideSampleTitle": "Start with the sample",
    "guideSampleBody": "Read the illustrated fable, then explore what its characters teach about AI agents. Creating your own story is coming later.",
    "guideReadTitle": "Read by scrolling",
    "guideReadBody": "Scroll through the scenes. The line at the top shows your progress. Your place is saved in this browser tab.",
    "guideContentsTitle": "Find the explanation",
    "guideContentsBody": "Open Contents to jump to the story, its explanation, or the ending.",
    "guideHomeTitle": "Return home",
    "guideHomeBody": "Home takes you back to Fable. Use Continue reading to return to your place."
  },
  "fr": {
    "shelf": "Accueil",
    "previewLabel": "Une découverte illustrée",
    "previewTitle": "Comprenez l’IA à travers une fable.",
    "previewSub": "Découvrez le raisonnement, la mémoire et les outils d’un agent IA dans la Salle des Affaires.",
    "readSample": "Lire l’exemple",
    "resume": "Reprendre la lecture",
    "sampleMeta": "Une histoire illustrée, puis son explication",
    "comingSoon": "Créer votre fable — bientôt",
    "previewNote": "La création de textes et d’images arrive plus tard. Cet exemple est prêt à lire.",
    "scrollCue": "Défiler pour continuer",
    "endLabel": "Fin",
    "decodedWord": "Explication",
    "afterStory": "L’histoire expliquée",
    "figureAlt": "Vue en coupe de la Salle des Affaires : le maître au centre, entouré du bureau de contexte, des archives, des coursiers, de l’intendant et des protections.",
    "figureCaption": "Une maison, plusieurs rôles. Les personnages représentent les couches expliquées ci-dessous.",
    "languageLabel": "Langue",
    "lightLabel": "Passer au thème clair",
    "darkLabel": "Passer au thème sombre",
    "closeLabel": "Fermer",
    "guideLabel": "Me guider",
    "guideClose": "Fermer le guide",
    "guideSkip": "Passer",
    "guideBack": "Retour",
    "guideNext": "Suivant",
    "guideFinish": "Terminer",
    "guideSampleTitle": "Commencez par l’exemple",
    "guideSampleBody": "Lisez la fable illustrée, puis découvrez ce que ses personnages enseignent sur les agents IA. La création de votre propre histoire viendra plus tard.",
    "guideReadTitle": "Lisez en faisant défiler",
    "guideReadBody": "Faites défiler les scènes. La ligne en haut indique votre progression. Votre position est conservée dans cet onglet.",
    "guideContentsTitle": "Trouvez l’explication",
    "guideContentsBody": "Ouvrez le sommaire pour accéder à l’histoire, à son explication ou à la fin.",
    "guideHomeTitle": "Revenez à l’accueil",
    "guideHomeBody": "Accueil vous ramène à Fable. Reprendre la lecture vous permet de retrouver votre position."
  },
  "da": {
    "shelf": "Hjem",
    "previewLabel": "En illustreret smagsprøve",
    "previewTitle": "Forstå AI gennem en fabel.",
    "previewSub": "Mød tankerne, hukommelsen og værktøjerne bag en AI-agent i Salen for Anliggender.",
    "readSample": "Læs eksemplet",
    "resume": "Læs videre",
    "sampleMeta": "En illustreret historie med en forklaring bagefter",
    "comingSoon": "Skab din egen — kommer snart",
    "previewNote": "Generering af historier og billeder er ikke tilgængelig endnu. Eksemplet er klar til at læse.",
    "scrollCue": "Rul for at fortsætte",
    "endLabel": "Slut",
    "decodedWord": "Forklaring",
    "afterStory": "Historien forklaret",
    "figureAlt": "Et tværsnit af Salen for Anliggender: mesteren i midten, omgivet af kontekstbordet, arkivet, løberne, forvalteren og sikkerhedsforanstaltningerne.",
    "figureCaption": "Ét hus, mange dele. Historiens personer repræsenterer lagene nedenfor.",
    "languageLabel": "Sprog",
    "lightLabel": "Skift til lyst tema",
    "darkLabel": "Skift til mørkt tema",
    "closeLabel": "Luk",
    "guideLabel": "Vis mig rundt",
    "guideClose": "Luk guiden",
    "guideSkip": "Spring over",
    "guideBack": "Tilbage",
    "guideNext": "Næste",
    "guideFinish": "Afslut",
    "guideSampleTitle": "Begynd med eksemplet",
    "guideSampleBody": "Læs den illustrerede fabel, og se derefter, hvad personerne lærer dig om AI-agenter. Du kan skabe din egen historie senere.",
    "guideReadTitle": "Læs ved at rulle",
    "guideReadBody": "Rul gennem scenerne. Linjen øverst viser din fremgang. Din plads gemmes i denne browserfane.",
    "guideContentsTitle": "Find forklaringen",
    "guideContentsBody": "Åbn indholdsfortegnelsen for at gå til historien, forklaringen eller slutningen.",
    "guideHomeTitle": "Vend hjem",
    "guideHomeBody": "Hjem fører dig tilbage til Fable. Vælg Læs videre for at vende tilbage til din plads."
  },
  "zh": {
    "shelf": "首页",
    "previewLabel": "插画学习体验",
    "previewTitle": "读一则寓言，理解人工智能。",
    "previewSub": "走进应事斋，认识智能体背后的思考、记忆与工具。",
    "readSample": "阅读示例",
    "resume": "继续阅读",
    "sampleMeta": "一则插画故事，以及故事背后的解释",
    "comingSoon": "创作自己的寓言 — 即将开放",
    "previewNote": "故事和图片生成尚未开放。你现在可以阅读这则示例寓言。",
    "scrollCue": "向下滚动，继续阅读",
    "endLabel": "结束",
    "decodedWord": "释义",
    "afterStory": "故事的含义",
    "figureAlt": "应事斋剖面图：先生居中，四周是铺案人的书桌、记忆档案、跑腿、管事与安全设施。",
    "figureCaption": "一座宅子，分工协作。故事人物对应下方解释的各个层次。",
    "languageLabel": "语言",
    "lightLabel": "切换日间模式",
    "darkLabel": "切换夜间模式",
    "closeLabel": "关闭",
    "guideLabel": "阅读指引",
    "guideClose": "关闭指引",
    "guideSkip": "跳过",
    "guideBack": "上一步",
    "guideNext": "下一步",
    "guideFinish": "完成",
    "guideSampleTitle": "从示例开始",
    "guideSampleBody": "先读插画寓言，再了解故事人物如何解释智能体。创作自己的故事将在之后开放。",
    "guideReadTitle": "滚动阅读",
    "guideReadBody": "向下滚动，逐幕阅读。顶部细线显示进度，当前浏览器标签页会保存你的阅读位置。",
    "guideContentsTitle": "找到释义",
    "guideContentsBody": "打开目录，可跳转到故事、释义或结尾。",
    "guideHomeTitle": "返回首页",
    "guideHomeBody": "首页按钮带你回到寓言首页。点击继续阅读，即可回到之前的位置。"
  }
};
for (const [lang, copy] of Object.entries(previewCopy)) Object.assign(window.FABLE.ui[lang], copy);
